appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{h({d(%Y-%m-%d %H:%M:%S)(utc)} - {l}: {m}{n})}"
  file_logger:
    kind: rolling_file
    path: "log/general/running.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} - {h({l})}: {m}{n}"
    policy:
      trigger:
        kind: size
        limit: 250kb
      roller:
        kind: fixed_window
        base: 1
        count: 4
        pattern: "log/general/old{}.log"
  database_mods:
    kind: rolling_file
    path: "log/running.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} | {h({l})} | {m}{n}"
    policy:
      trigger:
        kind: time
        interval: 1 day
        modulate: true
      roller:
        kind: fixed_window
        base: 1
        count: 10
        pattern: "log/old{}.log"

root:
  level: warn
  appenders:
    - stdout
    - file_logger

loggers:
  database:
    level: info
    appenders:
      - database_mods
    additive: false